# Tomcat
server:
  port: 8000
  servlet:
    session:
      cookie:
        timeout: 21600
    context-path: /api

spring:
  profiles:
    # 环境 dev|test|prod
    active: prod
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      # 单个文件上传大小
      max-file-size: 5MB
      # 单个上传请求中所有文件总大小
      max-request-size: 10MB


#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl